# Generated by Django 5.2.1 on 2025-07-12 08:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategories_name', models.CharField(max_length=50)),
                ('categories', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='swapshop.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='cart/image')),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
                ('is_available', models.BooleanField(default=True)),
                ('categary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swapshop.categories')),
                ('subCategary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swapshop.subcategories')),
            ],
        ),
    ]
