# Generated by Django 5.2.1 on 2025-07-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='report_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
